[package]
name = "bril-fuzzer"
version.workspace = true
edition.workspace = true

[dependencies]
bril.workspace = true 
slotmap.workspace = true
rand = "0.9.1"
rand_distr = "0.5.1"
rand_chacha = "0.9.0"
