[package]
name = "bril-analysis"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bril.workspace = true
slotmap.workspace = true
bril-cfg.workspace = true
fixedbitset.workspace = true
rayon.workspace = true
